name: e2echat
on: push
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: tsc
      - run: npm run bundle
      - run: pm2 start npm -- start
